### ISSUE TITLE
[MIGRATE] Migrate workflow functions to fibsem:v0.2-dev

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/autoliftout#32]
Migrate:

- [x] mill_lamella_trench
- [x] mill_lamella_jcut
- [x] liftout_lamella (Rohit)
- [x] land_needle_on_milled_lamella
- [x] land_lamella
- [x] reset_needle do later, need to reimplement it fullly 
- [x] thin_lamella (Rohit)
- [x] polish_lamella (lucile)
- [x] set_up_polish (lucile)
- [x] sputter_platinum_on_whole_sample_grid (Rohit)
- [x] mill lamella edge (Rohit)

**Comment by Rohit-Kannachel** [comment]
relative move on thermo needle (simulator) results in unknown error

![Image](https://github.com/DeMarcoLab/autoliftout/assets/111263763/de2403cd-07c7-4402-b1b0-ed62277b79cd)

**Comment by patrickcleeve2** [comment]
@Rohit-Kannachel @LucileNaegele done ✅
